version: '3.7'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  kafka-mq-connector:
    build:
      context: ./kafka-connect-mq-source
    volumes:
      - ./connector-config/connect-distributed.properties:/opt/kafka/config/connect-distributed.properties
    ports:
      - 8083:8083

  mq-broker:
    image: kafka-mq-bridging-showcase/mq-broker-source
    ports:
      - 9443:9443
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QM1"

  jaeger:
    image: jaegertracing/all-in-one:1.18.1
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  mq-producer:
    image: kafka-mq-bridging-showcase/mq-queue-producer:0
    environment:
      - MQ_HOST=mq-broker
      - MQ_PORT=1414
      - MQ_QUEUE=DEV.TO.KAFKA.QUEUE
      - MQ_USER=admin
      - MQ_PASSWORD=passw0rd
      - MQ_CHANNEL=DEV.ADMIN.SVRCONN
      - MQ_QMANAGER=QM1
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SERVICE_NAME=mq-producer
      - JAEGER_REPORTER_LOG_SPANS=true
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    ports:
      - 9080:9080
    depends_on:
      - mq-broker

  kafka-consumer:
    image: kafka-mq-bridging-showcase/kafka-consumer:0
    environment:
      - KAFKA_HOST=kafka:9092
      - KAFKA_TOPIC=DEV.FROM.MQ
      - KAFKA_CLIENT_ID=kafka-consumer
      - KAFKA_GROUP_ID=kafka-consumer
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SERVICE_NAME=kafka-consumer
      - JAEGER_REPORTER_LOG_SPANS=true
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    depends_on:
      - kafka
